#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    external_bar                 off:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap		\
    debug_output		 on

# # Space labels
yabai -m space 1 --label term
yabai -m space 2 --label browse
yabai -m space 3 --label music
# yabai -m space 4 --label media
# yabai -m space 5 --label misc

# # Rules for specific apps to be unmanaged
# yabai -m rule --add app="^System Preferences$" manage=off
# yabai -m rule --add app="^System Settings$" manage=off
# yabai -m rule --add app="^Calculator$" manage=off
# yabai -m rule --add app="^Karabiner-Elements$" manage=off
# yabai -m rule --add app="^QuickTime Player$" manage=off
# yabai -m rule --add app="^Finder$" manage=off
# yabai -m rule --add app="^Digital Colou?r Meter$" manage=off
# yabai -m rule --add app="^Preview$" manage=off
#
# # Rules for apps mentioned in requirements
# yabai -m rule --add app="^Google Chrome$" space=primary
# yabai -m rule --add app="^WezTerm$" space=terminal
# yabai -m rule --add app="^Spotify$" space=media


echo "yabai configuration loaded.."
